language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
before_install:
  - pip install codecov
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests/ --cov=./
after_success:
  - codecov --token=f49a12a6-a0fa-4979-9a96-163c5eebc8f0
