language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
before_install:
  - pip install codecov
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests/
after_success:
  - codecov --token=5d56a8d5-6ada-4102-9c60-647e420bfce7
